### PR TITLE
User Management compatible with mongo db

### PR DESCRIPTION
**Pull request by atomfrede**
First parts to make the user management work with mongodb.

@moifort I fixed some imports in your tests, but they are still failing. I'm not sure what your plans are with the tests.

### CODE REVIEW

**Comment by moifort** [comment]
@atomfrede don't worry abouts test, it was a first commit, the idea it's just to test very basically the repository. Thanks for your help!

**Comment by atomfrede** [comment]
If you like a can support you in writing some test

**Comment by moifort** [comment]
It's will be great, thank you a lot!

**Comment by atomfrede** [comment]
Ok, I'll see what I can do.

**Pull request merged**
